

ALTER TABLE ip.ip
/*DROP COLUMN description*/
# ADD location VARCHAR(255);
ADD owner VARCHAR(255);

INSERT INTO ip.ip (id, fromIP, toIP, location, owner) VALUES (NULL,'0.0.0.0','255.255.255.255','','' );

SELECT count(*)
FROM ip.ip;

TRUNCATE TABLE ip.ip;

DESC  ip.ip;

CREATE DATABASE db_ip
DEFAULT CHARACTER SET utf8;
DROP TABLE IF EXISTS db_IP.IP;
CREATE TABLE db_ip.ip(
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  start BIGINT NOT NULL,
  end BIGINT NOT NULL,
  location VARCHAR(255),
  remark VARCHAR(1024)
);

SHOW DATABASES;

SHOW TABLES FROM db_ip;

DESC db_ip.ip;